# Project-wide Gradle settings.

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete"
kotlin.code.style=official

# Suppress SDK version warning
android.suppressUnsupportedCompileSdk=34

# Enable build caching
org.gradle.caching=true

